apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-crowdcounting
  labels:
    app: drone-crowdcounting
spec:
  selector:
    matchLabels:
      app: drone-crowdcounting
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: drone-crowdcounting
    spec:
      containers:
        - name: drone-crowdcounting
          image: sergiocaputoo/visdrone
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 8000
          resources:
            requests:
              memory: 0.5Gi
              cpu: "0.25"
            limits:
              #nvidia.com/gpu: 1
              memory: 1Gi
              cpu: "0.5"

---
apiVersion: v1
kind: Service
metadata:
  name: drone-crowdcounting-service
  labels:
    app: drone-crowdcounting
spec:
  selector:
    app: drone-crowdcounting
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30000
      targetPort: 8000

#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: cuda-vector-add
#spec:
#  restartPolicy: OnFailure
#  containers:
#    - name: cuda-vector-add
#      # https://github.com/kubernetes/kubernetes/blob/v1.7.11/test/images/nvidia-cuda/Dockerfile
#      image: "k8s.gcr.io/cuda-vector-add:v0.1"
#      resources:
#        limits:
#          nvidia.com/gpu: 1
#  nodeSelector:
#    accelerator: nvidia-tesla-p100 # or nvidia-tesla-k80 etc.




# kubectl port-forward service/drone-crowdcounting-service 8000:8000