name: Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
#  docker:
#    runs-on: ubuntu-latest
#    env:
#      OS: ubuntu-latest
#      PYTHON: '3.9'
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v2
#      with:
#          fetch-depth: 0
#
#    - name: Setup Python
#      uses: actions/setup-python@v2.3.1
#      with:
#        python-version: 3.9
#
#    - name: Install dependecies
#      run: |
#        pip install dvc[gdrive]
#    - name: DVC pull
#      env:
#          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS }}
#      run: |
#        dvc pull exp/model.pth
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v1
#
#    - name: Login to DockerHub
#      uses: docker/login-action@v1
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#    - name: Build and push
#      id: docker_build
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        push: true
#        tags: sergiocaputoo/visdrone
  deploy:
    runs-on: ubuntu-latest
#    needs:
#      - docker
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: deploy
    - uses: actions/checkout@master
      run: |
        docker login visdrone.azurecr.io -u 00000000-0000-0000-0000-000000000000 -p ${{ secrets.AZURE_TOKEN }}
        az acr import --name visdrone --source docker.io/sergiocaputoo/visdrone --image visdrone:latest
        az container create -g visdrone -n visdrone --image sergiocaputoo/visdrone --port 80