name: Testing_ml

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:

  test_metrics:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'new model') }}
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: 3.9
    - name: Install dependecies
      run: |
        pip install -r requirements_test.txt
        pip install dvc[gdrive]
    - name: DVC pull
      env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS }}
      run: |
        dvc pull exp/train/model.pth
    - name: Test metrics
      run: |
        PYTHONPATH='src' pytest -m "ml" tests/
        cp exp/train/model.pth exp/model.pth
        dvc push exp/model.pth